import type { CertificateTemplate } from "./types"

export const DEFAULT_CERTIFICATE_TEMPLATES: CertificateTemplate[] = [
  {
    id: "dev-fullstack-mastery",
    title: "Full-Stack Software Engineering Mastery",
    subtitle: "Professional Software Engineering Track Completion",
    category: "Training",
    division: "Development Division",
    divisionSlug: "dev",
    accentColor: "#0284c7", // Sky Blue / Cyan
    secondaryColor: "#0369a1",
    description: "Designed for full-stack software tracks, covering modern web systems, API architectures, and open-source software contributions.",
    downloadsCount: 142,
    isFeatured: true,
    fileName: "CSEC_FullStack_Mastery_Template.pptx",
    signatoryLeftTitle: "President, CSEC-ASTU",
    signatoryLeftName: "Executive President",
    signatoryRightTitle: "Development Division Head",
    signatoryRightName: "Head of Development",
    paperStyle: "cyber-neon",
  },
  {
    id: "cp-algorithmic-distinction",
    title: "Algorithmic Problem Solving Distinction",
    subtitle: "Competitive Programming Benchmark Award",
    category: "Competition",
    division: "Competitive Programming",
    divisionSlug: "cp",
    accentColor: "#059669", // Emerald Green
    secondaryColor: "#047857",
    description: "Tailored for programming contest qualifiers, ICPC finalists, and high-ranking algorithmic benchmark performers.",
    downloadsCount: 128,
    isFeatured: true,
    fileName: "CSEC_CP_Distinction_Template.pptx",
    signatoryLeftTitle: "President, CSEC-ASTU",
    signatoryLeftName: "Executive President",
    signatoryRightTitle: "Competitive Programming Head",
    signatoryRightName: "Head of CP",
    paperStyle: "royal-emerald",
  },
  {
    id: "cyber-defense-mastery",
    title: "Offensive & Defensive Security Track",
    subtitle: "Cybersecurity Training & CTF Completion",
    category: "Training",
    division: "Cybersecurity",
    divisionSlug: "cyber",
    accentColor: "#dc2626", // Crimson Red
    secondaryColor: "#b91c1c",
    description: "Sleek dark-bordered security credential for members completing hands-on network penetration testing, system hardening, and CTF challenges.",
    downloadsCount: 96,
    fileName: "CSEC_Cybersecurity_Mastery_Template.pptx",
    signatoryLeftTitle: "President, CSEC-ASTU",
    signatoryLeftName: "Executive President",
    signatoryRightTitle: "Cybersecurity Division Head",
    signatoryRightName: "Head of Security",
    paperStyle: "cyber-neon",
  },
  {
    id: "data-science-ai-mastery",
    title: "Applied Machine Learning & Data Engineering",
    subtitle: "Data Science & AI Curriculum Completion",
    category: "Academic",
    division: "Data Science",
    divisionSlug: "datascience",
    accentColor: "#7c3aed", // Deep Violet
    secondaryColor: "#6d28d9",
    description: "Clean academic presentation for machine learning pipelines, predictive modeling cohorts, and research workshops.",
    downloadsCount: 84,
    fileName: "CSEC_DataScience_AI_Template.pptx",
    signatoryLeftTitle: "President, CSEC-ASTU",
    signatoryLeftName: "Executive President",
    signatoryRightTitle: "Data Science Division Head",
    signatoryRightName: "Head of Data Science",
    paperStyle: "academic-navy",
  },
  {
    id: "capacity-mentorship-delivery",
    title: "Technical Mentorship & Workshop Delivery",
    subtitle: "Peer Education & Community Leadership Honor",
    category: "Workshop",
    division: "Capacity Building",
    divisionSlug: "cbd",
    accentColor: "#d97706", // Warm Amber
    secondaryColor: "#b45309",
    description: "Warm gold foil prestige layout for student instructors, peer tutoring leads, and technical workshop speakers.",
    downloadsCount: 110,
    fileName: "CSEC_Capacity_Mentorship_Template.pptx",
    signatoryLeftTitle: "President, CSEC-ASTU",
    signatoryLeftName: "Executive President",
    signatoryRightTitle: "Capacity Building Division Head",
    signatoryRightName: "Head of Capacity Building",
    paperStyle: "classic-gold",
  },
  {
    id: "blockchain-smart-contract",
    title: "Web3 & Smart Contract Engineering",
    subtitle: "Decentralized Architecture Track Completion",
    category: "Achievement",
    division: "Blockchain team",
    divisionSlug: "blockchain",
    accentColor: "#9333ea", // Solana Purple
    secondaryColor: "#7e22ce",
    description: "Modern cryptographically accented design for smart contract audits, decentralized application development, and protocol workshops.",
    downloadsCount: 65,
    fileName: "CSEC_Blockchain_Engineering_Template.pptx",
    signatoryLeftTitle: "President, CSEC-ASTU",
    signatoryLeftName: "Executive President",
    signatoryRightTitle: "Blockchain Lead",
    signatoryRightName: "Head of Blockchain",
    paperStyle: "cyber-neon",
  },
  {
    id: "social-media-branding",
    title: "Creative Media & Digital Brand Direction",
    subtitle: "Multimedia & Design Excellence Honor",
    category: "Participation",
    division: "Social Media",
    divisionSlug: "media",
    accentColor: "#e11d48", // Rose / Coral
    secondaryColor: "#be123c",
    description: "Vibrant and balanced editorial layout for student designers, photographers, content creators, and brand directors.",
    downloadsCount: 71,
    fileName: "CSEC_Media_Brand_Template.pptx",
    signatoryLeftTitle: "President, CSEC-ASTU",
    signatoryLeftName: "Executive President",
    signatoryRightTitle: "Social Media Division Head",
    signatoryRightName: "Head of Branding",
    paperStyle: "clean-monochrome",
  },
  {
    id: "executive-leadership-honor",
    title: "Executive Leadership & Council Honor",
    subtitle: "Club-Wide Executive Governance Service",
    category: "Leadership",
    division: "Executive Council",
    divisionSlug: "exec",
    accentColor: "#ca8a04", // Gold & Platinum
    secondaryColor: "#a16207",
    description: "Formal presidential commendation for outgoing Division Heads, Vice President, and Executive Board officers.",
    downloadsCount: 52,
    fileName: "CSEC_Executive_Leadership_Template.pptx",
    signatoryLeftTitle: "President, CSEC-ASTU",
    signatoryLeftName: "President",
    signatoryRightTitle: "Faculty Advisor, ASTU",
    signatoryRightName: "Staff Advisor",
    paperStyle: "classic-gold",
  },
  {
    id: "hackathon-distinction",
    title: "Annual University Hackathon Finalist",
    subtitle: "Product Innovation & Rapid Prototyping",
    category: "Competition",
    division: "Club-Wide",
    divisionSlug: "all",
    accentColor: "#2563eb", // Royal Blue
    secondaryColor: "#1d4ed8",
    description: "Commemorative hackathon certificate for team leads and finalists in the university-wide annual software challenge.",
    downloadsCount: 119,
    fileName: "CSEC_Hackathon_Finalist_Template.pptx",
    signatoryLeftTitle: "President, CSEC-ASTU",
    signatoryLeftName: "Executive President",
    signatoryRightTitle: "Hackathon Jury Lead",
    signatoryRightName: "Lead Judge",
    paperStyle: "clean-monochrome",
  },
  {
    id: "academic-excellence-honor",
    title: "Extracurricular Engineering Excellence",
    subtitle: "Academic Year Performance Honor",
    category: "Academic",
    division: "Club-Wide",
    divisionSlug: "all",
    accentColor: "#475569", // Slate / Charcoal
    secondaryColor: "#334155",
    description: "Minimalist corporate certificate for members who sustained top attendance and top leaderboard rankings across the year.",
    downloadsCount: 88,
    fileName: "CSEC_Engineering_Excellence_Template.pptx",
    signatoryLeftTitle: "President, CSEC-ASTU",
    signatoryLeftName: "Executive President",
    signatoryRightTitle: "Vice President, CSEC-ASTU",
    signatoryRightName: "Vice President",
    paperStyle: "academic-navy",
  },
]
