import type { AttendanceMatrixOut } from "@/lib/api/types"

export const DEMO_ATTENDANCE_MATRIX: AttendanceMatrixOut = {
  division_id: null,
  days: 30,
  start_date: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
  end_date: new Date().toISOString(),
  kpi: {
    total_sessions: 5,
    total_members: 12,
    average_turnout_rate: 78.3,
    on_time_rate: 76.6,
    total_checkins: 47,
    total_late_checkins: 11,
  },
  columns: [
    {
      id: "sess-1",
      date: "2026-09-02T14:00:00Z",
      date_display: "Sep 02",
      task_title: "Reverse Engineering 101",
      division_name: "Cybersecurity",
      is_active: false,
    },
    {
      id: "sess-2",
      date: "2026-09-05T14:00:00Z",
      date_display: "Sep 05",
      task_title: "Next.js & FastAPI Architecture",
      division_name: "Development",
      is_active: false,
    },
    {
      id: "sess-3",
      date: "2026-09-08T14:00:00Z",
      date_display: "Sep 08",
      task_title: "Graph Algorithms Sprint",
      division_name: "Competitive Programming",
      is_active: false,
    },
    {
      id: "sess-4",
      date: "2026-09-12T14:00:00Z",
      date_display: "Sep 12",
      task_title: "Packet Inspection & Defense",
      division_name: "Cybersecurity",
      is_active: false,
    },
    {
      id: "sess-5",
      date: "2026-09-15T14:00:00Z",
      date_display: "Sep 15",
      task_title: "Transformer Models Deep Dive",
      division_name: "Data Science & AI",
      is_active: true,
    },
  ],
  rows: [
    {
      member_id: "m-1",
      full_name: "Bereket Ketema",
      email: "bereket.k@astu.edu.et",
      profile_image_url: null,
      division_id: "div-cyber",
      division_name: "Cybersecurity",
      role: "division_head",
      stats: {
        attended_count: 5,
        total_sessions: 5,
        late_count: 0,
        on_time_count: 5,
        attendance_rate: 100,
      },
      sessions: {
        "sess-1": { status: "present", delay_minutes: 3, claimed_at: "2026-09-02T14:03:00Z", points_awarded: 10 },
        "sess-2": { status: "present", delay_minutes: 4, claimed_at: "2026-09-05T14:04:00Z", points_awarded: 10 },
        "sess-3": { status: "present", delay_minutes: 2, claimed_at: "2026-09-08T14:02:00Z", points_awarded: 10 },
        "sess-4": { status: "present", delay_minutes: 5, claimed_at: "2026-09-12T14:05:00Z", points_awarded: 10 },
        "sess-5": { status: "present", delay_minutes: 6, claimed_at: "2026-09-15T14:06:00Z", points_awarded: 10 },
      },
    },
    {
      member_id: "m-2",
      full_name: "Eyob Aragie",
      email: "eyob.a@astu.edu.et",
      profile_image_url: null,
      division_id: "div-dev",
      division_name: "Development",
      role: "member",
      stats: {
        attended_count: 4,
        total_sessions: 5,
        late_count: 1,
        on_time_count: 3,
        attendance_rate: 80,
      },
      sessions: {
        "sess-1": { status: "present", delay_minutes: 7, claimed_at: "2026-09-02T14:07:00Z", points_awarded: 10 },
        "sess-2": { status: "present", delay_minutes: 5, claimed_at: "2026-09-05T14:05:00Z", points_awarded: 10 },
        "sess-3": { status: "absent", delay_minutes: null, claimed_at: null, points_awarded: 0 },
        "sess-4": { status: "late", delay_minutes: 22, claimed_at: "2026-09-12T14:22:00Z", points_awarded: 10 },
        "sess-5": { status: "present", delay_minutes: 4, claimed_at: "2026-09-15T14:04:00Z", points_awarded: 10 },
      },
    },
    {
      member_id: "m-3",
      full_name: "Firaol Kefeni",
      email: "firaol.k@astu.edu.et",
      profile_image_url: null,
      division_id: "div-cp",
      division_name: "Competitive Programming",
      role: "member",
      stats: {
        attended_count: 4,
        total_sessions: 5,
        late_count: 0,
        on_time_count: 4,
        attendance_rate: 80,
      },
      sessions: {
        "sess-1": { status: "present", delay_minutes: 5, claimed_at: "2026-09-02T14:05:00Z", points_awarded: 10 },
        "sess-2": { status: "present", delay_minutes: 6, claimed_at: "2026-09-05T14:06:00Z", points_awarded: 10 },
        "sess-3": { status: "present", delay_minutes: 3, claimed_at: "2026-09-08T14:03:00Z", points_awarded: 10 },
        "sess-4": { status: "absent", delay_minutes: null, claimed_at: null, points_awarded: 0 },
        "sess-5": { status: "present", delay_minutes: 8, claimed_at: "2026-09-15T14:08:00Z", points_awarded: 10 },
      },
    },
    {
      member_id: "m-4",
      full_name: "Fireweld Tesfaye",
      email: "fireweld.t@astu.edu.et",
      profile_image_url: null,
      division_id: "div-cyber",
      division_name: "Cybersecurity",
      role: "member",
      stats: {
        attended_count: 4,
        total_sessions: 5,
        late_count: 2,
        on_time_count: 2,
        attendance_rate: 80,
      },
      sessions: {
        "sess-1": { status: "late", delay_minutes: 19, claimed_at: "2026-09-02T14:19:00Z", points_awarded: 10 },
        "sess-2": { status: "present", delay_minutes: 10, claimed_at: "2026-09-05T14:10:00Z", points_awarded: 10 },
        "sess-3": { status: "absent", delay_minutes: null, claimed_at: null, points_awarded: 0 },
        "sess-4": { status: "late", delay_minutes: 27, claimed_at: "2026-09-12T14:27:00Z", points_awarded: 10 },
        "sess-5": { status: "present", delay_minutes: 8, claimed_at: "2026-09-15T14:08:00Z", points_awarded: 10 },
      },
    },
    {
      member_id: "m-5",
      full_name: "Menwuyelet Temesgen",
      email: "menwuyelet.t@astu.edu.et",
      profile_image_url: null,
      division_id: "div-dev",
      division_name: "Development",
      role: "member",
      stats: {
        attended_count: 5,
        total_sessions: 5,
        late_count: 1,
        on_time_count: 4,
        attendance_rate: 100,
      },
      sessions: {
        "sess-1": { status: "present", delay_minutes: 6, claimed_at: "2026-09-02T14:06:00Z", points_awarded: 10 },
        "sess-2": { status: "present", delay_minutes: 4, claimed_at: "2026-09-05T14:04:00Z", points_awarded: 10 },
        "sess-3": { status: "late", delay_minutes: 18, claimed_at: "2026-09-08T14:18:00Z", points_awarded: 10 },
        "sess-4": { status: "present", delay_minutes: 9, claimed_at: "2026-09-12T14:09:00Z", points_awarded: 10 },
        "sess-5": { status: "present", delay_minutes: 5, claimed_at: "2026-09-15T14:05:00Z", points_awarded: 10 },
      },
    },
    {
      member_id: "m-6",
      full_name: "Merga Shasho",
      email: "merga.s@astu.edu.et",
      profile_image_url: null,
      division_id: "div-ai",
      division_name: "Data Science & AI",
      role: "member",
      stats: {
        attended_count: 3,
        total_sessions: 5,
        late_count: 1,
        on_time_count: 2,
        attendance_rate: 60,
      },
      sessions: {
        "sess-1": { status: "absent", delay_minutes: null, claimed_at: null, points_awarded: 0 },
        "sess-2": { status: "present", delay_minutes: 8, claimed_at: "2026-09-05T14:08:00Z", points_awarded: 10 },
        "sess-3": { status: "absent", delay_minutes: null, claimed_at: null, points_awarded: 0 },
        "sess-4": { status: "late", delay_minutes: 24, claimed_at: "2026-09-12T14:24:00Z", points_awarded: 10 },
        "sess-5": { status: "present", delay_minutes: 5, claimed_at: "2026-09-15T14:05:00Z", points_awarded: 10 },
      },
    },
    {
      member_id: "m-7",
      full_name: "Moges Tesema",
      email: "moges.t@astu.edu.et",
      profile_image_url: null,
      division_id: "div-cyber",
      division_name: "Cybersecurity",
      role: "member",
      stats: {
        attended_count: 4,
        total_sessions: 5,
        late_count: 1,
        on_time_count: 3,
        attendance_rate: 80,
      },
      sessions: {
        "sess-1": { status: "present", delay_minutes: 12, claimed_at: "2026-09-02T14:12:00Z", points_awarded: 10 },
        "sess-2": { status: "absent", delay_minutes: null, claimed_at: null, points_awarded: 0 },
        "sess-3": { status: "present", delay_minutes: 7, claimed_at: "2026-09-08T14:07:00Z", points_awarded: 10 },
        "sess-4": { status: "present", delay_minutes: 5, claimed_at: "2026-09-12T14:05:00Z", points_awarded: 10 },
        "sess-5": { status: "late", delay_minutes: 21, claimed_at: "2026-09-15T14:21:00Z", points_awarded: 10 },
      },
    },
    {
      member_id: "m-8",
      full_name: "Nigusu Demelash",
      email: "nigusu.d@astu.edu.et",
      profile_image_url: null,
      division_id: "div-cp",
      division_name: "Competitive Programming",
      role: "member",
      stats: {
        attended_count: 3,
        total_sessions: 5,
        late_count: 2,
        on_time_count: 1,
        attendance_rate: 60,
      },
      sessions: {
        "sess-1": { status: "absent", delay_minutes: null, claimed_at: null, points_awarded: 0 },
        "sess-2": { status: "late", delay_minutes: 25, claimed_at: "2026-09-05T14:25:00Z", points_awarded: 10 },
        "sess-3": { status: "present", delay_minutes: 5, claimed_at: "2026-09-08T14:05:00Z", points_awarded: 10 },
        "sess-4": { status: "absent", delay_minutes: null, claimed_at: null, points_awarded: 0 },
        "sess-5": { status: "late", delay_minutes: 18, claimed_at: "2026-09-15T14:18:00Z", points_awarded: 10 },
      },
    },
    {
      member_id: "m-9",
      full_name: "Chala Bekele",
      email: "chala.b@astu.edu.et",
      profile_image_url: null,
      division_id: "div-cyber",
      division_name: "Cybersecurity",
      role: "member",
      stats: {
        attended_count: 5,
        total_sessions: 5,
        late_count: 0,
        on_time_count: 5,
        attendance_rate: 100,
      },
      sessions: {
        "sess-1": { status: "present", delay_minutes: 2, claimed_at: "2026-09-02T14:02:00Z", points_awarded: 10 },
        "sess-2": { status: "present", delay_minutes: 5, claimed_at: "2026-09-05T14:05:00Z", points_awarded: 10 },
        "sess-3": { status: "present", delay_minutes: 3, claimed_at: "2026-09-08T14:03:00Z", points_awarded: 10 },
        "sess-4": { status: "present", delay_minutes: 4, claimed_at: "2026-09-12T14:04:00Z", points_awarded: 10 },
        "sess-5": { status: "present", delay_minutes: 7, claimed_at: "2026-09-15T14:07:00Z", points_awarded: 10 },
      },
    },
    {
      member_id: "m-10",
      full_name: "Abebe Kebede",
      email: "abebe.k@astu.edu.et",
      profile_image_url: null,
      division_id: "div-dev",
      division_name: "Development",
      role: "member",
      stats: {
        attended_count: 4,
        total_sessions: 5,
        late_count: 1,
        on_time_count: 3,
        attendance_rate: 80,
      },
      sessions: {
        "sess-1": { status: "present", delay_minutes: 4, claimed_at: "2026-09-02T14:04:00Z", points_awarded: 10 },
        "sess-2": { status: "present", delay_minutes: 6, claimed_at: "2026-09-05T14:06:00Z", points_awarded: 10 },
        "sess-3": { status: "late", delay_minutes: 17, claimed_at: "2026-09-08T14:17:00Z", points_awarded: 10 },
        "sess-4": { status: "present", delay_minutes: 5, claimed_at: "2026-09-12T14:05:00Z", points_awarded: 10 },
        "sess-5": { status: "absent", delay_minutes: null, claimed_at: null, points_awarded: 0 },
      },
    },
    {
      member_id: "m-11",
      full_name: "Biruk Tesfaye",
      email: "biruk.t@astu.edu.et",
      profile_image_url: null,
      division_id: "div-cp",
      division_name: "Competitive Programming",
      role: "member",
      stats: {
        attended_count: 3,
        total_sessions: 5,
        late_count: 1,
        on_time_count: 2,
        attendance_rate: 60,
      },
      sessions: {
        "sess-1": { status: "absent", delay_minutes: null, claimed_at: null, points_awarded: 0 },
        "sess-2": { status: "present", delay_minutes: 11, claimed_at: "2026-09-05T14:11:00Z", points_awarded: 10 },
        "sess-3": { status: "present", delay_minutes: 5, claimed_at: "2026-09-08T14:05:00Z", points_awarded: 10 },
        "sess-4": { status: "late", delay_minutes: 23, claimed_at: "2026-09-12T14:23:00Z", points_awarded: 10 },
        "sess-5": { status: "absent", delay_minutes: null, claimed_at: null, points_awarded: 0 },
      },
    },
    {
      member_id: "m-12",
      full_name: "Hawi Girma",
      email: "hawi.g@astu.edu.et",
      profile_image_url: null,
      division_id: "div-ai",
      division_name: "Data Science & AI",
      role: "member",
      stats: {
        attended_count: 3,
        total_sessions: 5,
        late_count: 0,
        on_time_count: 3,
        attendance_rate: 60,
      },
      sessions: {
        "sess-1": { status: "present", delay_minutes: 9, claimed_at: "2026-09-02T14:09:00Z", points_awarded: 10 },
        "sess-2": { status: "absent", delay_minutes: null, claimed_at: null, points_awarded: 0 },
        "sess-3": { status: "present", delay_minutes: 5, claimed_at: "2026-09-08T14:05:00Z", points_awarded: 10 },
        "sess-4": { status: "absent", delay_minutes: null, claimed_at: null, points_awarded: 0 },
        "sess-5": { status: "present", delay_minutes: 4, claimed_at: "2026-09-15T14:04:00Z", points_awarded: 10 },
      },
    },
  ],
}
